FROM python:3.12-slim

WORKDIR /app/backend

# Copy the entire backend directory contents
COPY backend/ .

RUN pip install --no-cache-dir -r requirements.txt

# Add this environment variable
ENV PYTHONUNBUFFERED=1

CMD ["python", "-u", "scheduler.py"]